// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:650589dc-b299-4416-bb2c-199cadec1dd2",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_xdxhITAbF",
    "aws_user_pools_web_client_id": "7jqgu5hlt8uvv02f14cjmt1v1b",
    "aws_appsync_graphqlEndpoint": "https://fdn33b2fejgxrba5rb6et2gyke.appsync-api.ap-southeast-2.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_content_delivery_bucket": "amplifynotes",
    "aws_content_delivery_bucket_region": "ap-southeast-2",
    "aws_content_delivery_url": "https://d2jaejh2wy167t.cloudfront.net"
};


export default awsmobile;
